{
  .name = "GEN_INT_STATUS",
  .address = 0x104,
},
{
  .name = "VGA_RENDER_CONTROL",
  .address = 0x300,
},
{
  .name = "VGA_SEQUENCER_RESET_CONTROL",
  .address = 0x304,
},
{
  .name = "VGA_MODE_CONTROL",
  .address = 0x308,
},
{
  .name = "VGA_SURFACE_PITCH_SELECT",
  .address = 0x30c,
},
{
  .name = "VGA_MEMORY_BASE_ADDRESS",
  .address = 0x310,
},
{
  .name = "VGA_DISPBUF1_SURFACE_ADDR",
  .address = 0x318,
},
{
  .name = "VGA_DISPBUF2_SURFACE_ADDR",
  .address = 0x320,
},
{
  .name = "VGA_HDP_CONTROL",
  .address = 0x328,
},
{
  .name = "VGA_CACHE_CONTROL",
  .address = 0x32c,
},
{
  .name = "D1VGA_CONTROL",
  .address = 0x330,
},
{
  .name = "D2VGA_CONTROL",
  .address = 0x338,
},
{
  .name = "VGA_STATUS",
  .address = 0x340,
},
{
  .name = "VGA_INTERRUPT_CONTROL",
  .address = 0x344,
},
{
  .name = "VGA_STATUS_CLEAR",
  .address = 0x348,
},
{
  .name = "VGA_INTERRUPT_STATUS",
  .address = 0x34c,
},
{
  .name = "VGA_MAIN_CONTROL",
  .address = 0x350,
},
{
  .name = "VGA_TEST_CONTROL",
  .address = 0x354,
},
{
  .name = "VGA_DEBUG_READBACK_INDEX",
  .address = 0x358,
},
{
  .name = "VGA_DEBUG_READBACK_DATA",
  .address = 0x35c,
},
{
  .name = "VGA_MEM_WRITE_PAGE_ADDR",
  .address = 0x38,
},
{
  .name = "CRTC8_IDX",
  .address = 0x3b4,
},
{
  .name = "CRTC8_IDX",
  .address = 0x3b4,
},
{
  .name = "CRTC8_DATA",
  .address = 0x3b5,
},
{
  .name = "CRTC8_DATA",
  .address = 0x3b5,
},
{
  .name = "GENFC_WT",
  .address = 0x3ba,
},
{
  .name = "GENS1",
  .address = 0x3ba,
},
{
  .name = "VGA_MEM_READ_PAGE_ADDR",
  .address = 0x3c,
},
{
  .name = "ATTRDW",
  .address = 0x3c0,
},
{
  .name = "ATTRX",
  .address = 0x3c0,
},
{
  .name = "ATTRDR",
  .address = 0x3c1,
},
{
  .name = "GENMO_WT",
  .address = 0x3c2,
},
{
  .name = "GENMO_WT",
  .address = 0x3c2,
},
{
  .name = "GENS0",
  .address = 0x3c2,
},
{
  .name = "SEQ8_IDX",
  .address = 0x3c4,
},
{
  .name = "SEQ8_IDX",
  .address = 0x3c4,
},
{
  .name = "SEQ8_DATA",
  .address = 0x3c5,
},
{
  .name = "SEQ8_DATA",
  .address = 0x3c5,
},
{
  .name = "DAC_MASK",
  .address = 0x3c6,
},
{
  .name = "DAC_R_INDEX",
  .address = 0x3c7,
},
{
  .name = "DAC_W_INDEX",
  .address = 0x3c8,
},
{
  .name = "DAC_DATA",
  .address = 0x3c9,
},
{
  .name = "GENFC_RD",
  .address = 0x3ca,
},
{
  .name = "GENMO_RD",
  .address = 0x3cc,
},
{
  .name = "GENMO_RD",
  .address = 0x3cc,
},
{
  .name = "GRPH8_IDX",
  .address = 0x3ce,
},
{
  .name = "GRPH8_IDX",
  .address = 0x3ce,
},
{
  .name = "GRPH8_DATA",
  .address = 0x3cf,
},
{
  .name = "GRPH8_DATA",
  .address = 0x3cf,
},
{
  .name = "D1CRTC_H_TOTAL",
  .address = 0x6000,
},
{
  .name = "D1CRTC_H_BLANK_START_END",
  .address = 0x6004,
},
{
  .name = "D1CRTC_H_SYNC_A",
  .address = 0x6008,
},
{
  .name = "D1CRTC_H_SYNC_A_CNTL",
  .address = 0x600c,
},
{
  .name = "D1CRTC_H_SYNC_B",
  .address = 0x6010,
},
{
  .name = "D1CRTC_H_SYNC_B_CNTL",
  .address = 0x6014,
},
{
  .name = "D1CRTC_V_TOTAL",
  .address = 0x6020,
},
{
  .name = "D1CRTC_V_BLANK_START_END",
  .address = 0x6024,
},
{
  .name = "D1CRTC_V_SYNC_A",
  .address = 0x6028,
},
{
  .name = "D1CRTC_V_SYNC_A_CNTL",
  .address = 0x602c,
},
{
  .name = "D1CRTC_V_SYNC_B",
  .address = 0x6030,
},
{
  .name = "D1CRTC_V_SYNC_B_CNTL",
  .address = 0x6034,
},
{
  .name = "D1CRTC_TRIGA_CNTL",
  .address = 0x6060,
},
{
  .name = "D1CRTC_TRIGA_MANUAL_TRIG",
  .address = 0x6064,
},
{
  .name = "D1CRTC_TRIGB_CNTL",
  .address = 0x6068,
},
{
  .name = "D1CRTC_TRIGB_MANUAL_TRIG",
  .address = 0x606c,
},
{
  .name = "D1CRTC_FORCE_COUNT_NOW_CNTL",
  .address = 0x6070,
},
{
  .name = "D1CRTC_FLOW_CONTROL",
  .address = 0x6074,
},
{
  .name = "D1CRTC_PIXEL_DATA_READBACK",
  .address = 0x6078,
},
{
  .name = "D1CRTC_STEREO_FORCE_NEXT_EYE",
  .address = 0x607c,
},
{
  .name = "D1CRTC_CONTROL",
  .address = 0x6080,
},
{
  .name = "D1CRTC_BLANK_CONTROL",
  .address = 0x6084,
},
{
  .name = "D1CRTC_INTERLACE_CONTROL",
  .address = 0x6088,
},
{
  .name = "D1CRTC_INTERLACE_STATUS",
  .address = 0x608c,
},
{
  .name = "D1CRTC_BLANK_DATA_COLOR",
  .address = 0x6090,
},
{
  .name = "D1CRTC_OVERSCAN_COLOR",
  .address = 0x6094,
},
{
  .name = "D1CRTC_BLACK_COLOR",
  .address = 0x6098,
},
{
  .name = "D1CRTC_STATUS",
  .address = 0x609c,
},
{
  .name = "D1CRTC_STATUS_POSITION",
  .address = 0x60a0,
},
{
  .name = "D1CRTC_STATUS_FRAME_COUNT",
  .address = 0x60a4,
},
{
  .name = "D1CRTC_STATUS_VF_COUNT",
  .address = 0x60a8,
},
{
  .name = "D1CRTC_STATUS_HV_COUNT",
  .address = 0x60ac,
},
{
  .name = "D1CRTC_COUNT_RESET",
  .address = 0x60b0,
},
{
  .name = "D1CRTC_COUNT_CONTROL",
  .address = 0x60b4,
},
{
  .name = "D1CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE",
  .address = 0x60b8,
},
{
  .name = "D1CRTC_VERT_SYNC_CONTROL",
  .address = 0x60bc,
},
{
  .name = "D1CRTC_STEREO_STATUS",
  .address = 0x60c0,
},
{
  .name = "D1CRTC_STEREO_CONTROL",
  .address = 0x60c4,
},
{
  .name = "D1CRTC_SNAPSHOT_STATUS",
  .address = 0x60c8,
},
{
  .name = "D1CRTC_SNAPSHOT_CONTROL",
  .address = 0x60cc,
},
{
  .name = "D1CRTC_SNAPSHOT_POSITION",
  .address = 0x60d0,
},
{
  .name = "D1CRTC_SNAPSHOT_FRAME",
  .address = 0x60d4,
},
{
  .name = "D1CRTC_START_LINE_CONTROL",
  .address = 0x60d8,
},
{
  .name = "D1CRTC_INTERRUPT_CONTROL",
  .address = 0x60dc,
},
{
  .name = "D1MODE_MASTER_UPDATE_LOCK",
  .address = 0x60e0,
},
{
  .name = "D1MODE_MASTER_UPDATE_MODE",
  .address = 0x60e4,
},
{
  .name = "D1CRTC_UPDATE_LOCK",
  .address = 0x60e8,
},
{
  .name = "D1CRTC_DOUBLE_BUFFER_CONTROL",
  .address = 0x60ec,
},
{
  .name = "D1CRTC_VGA_PARAMETER_CAPTURE_MODE",
  .address = 0x60f0,
},
{
  .name = "DC_CRTC_MASTER_EN",
  .address = 0x60f8,
},
{
  .name = "DC_CRTC_TV_CONTROL",
  .address = 0x60fc,
},
{
  .name = "D1GRPH_ENABLE",
  .address = 0x6100,
},
{
  .name = "D1GRPH_CONTROL",
  .address = 0x6104,
},
{
  .name = "D1GRPH_LUT_SEL",
  .address = 0x6108,
},
{
  .name = "D1GRPH_PRIMARY_SURFACE_ADDRESS",
  .address = 0x6110,
},
{
  .name = "D1GRPH_SECONDARY_SURFACE_ADDRESS",
  .address = 0x6118,
},
{
  .name = "D1GRPH_PITCH",
  .address = 0x6120,
},
{
  .name = "D1GRPH_SURFACE_OFFSET_X",
  .address = 0x6124,
},
{
  .name = "D1GRPH_SURFACE_OFFSET_Y",
  .address = 0x6128,
},
{
  .name = "D1GRPH_X_START",
  .address = 0x612c,
},
{
  .name = "D1GRPH_Y_START",
  .address = 0x6130,
},
{
  .name = "D1GRPH_X_END",
  .address = 0x6134,
},
{
  .name = "D1GRPH_Y_END",
  .address = 0x6138,
},
{
  .name = "D1COLOR_SPACE_CONVERT",
  .address = 0x613c,
},
{
  .name = "D1OVL_COLOR_MATRIX_TRANSFORMATION_CNTL",
  .address = 0x6140,
},
{
  .name = "D1GRPH_UPDATE",
  .address = 0x6144,
},
{
  .name = "D1GRPH_FLIP_CONTROL",
  .address = 0x6148,
},
{
  .name = "D1GRPH_SURFACE_ADDRESS_INUSE",
  .address = 0x614c,
},
{
  .name = "D1OVL_ENABLE",
  .address = 0x6180,
},
{
  .name = "D1OVL_CONTROL1",
  .address = 0x6184,
},
{
  .name = "D1OVL_CONTROL2",
  .address = 0x6188,
},
{
  .name = "D1OVL_SURFACE_ADDRESS",
  .address = 0x6190,
},
{
  .name = "D1OVL_PITCH",
  .address = 0x6198,
},
{
  .name = "D1OVL_SURFACE_OFFSET_X",
  .address = 0x619c,
},
{
  .name = "D1OVL_SURFACE_OFFSET_Y",
  .address = 0x61a0,
},
{
  .name = "D1OVL_START",
  .address = 0x61a4,
},
{
  .name = "D1OVL_END",
  .address = 0x61a8,
},
{
  .name = "D1OVL_UPDATE",
  .address = 0x61ac,
},
{
  .name = "D1OVL_SURFACE_ADDRESS_INUSE",
  .address = 0x61b0,
},
{
  .name = "D1OVL_MATRIX_TRANSFORM_EN",
  .address = 0x6200,
},
{
  .name = "D1OVL_MATRIX_COEF_1_1",
  .address = 0x6204,
},
{
  .name = "D1OVL_MATRIX_COEF_1_2",
  .address = 0x6208,
},
{
  .name = "D1OVL_MATRIX_COEF_1_3",
  .address = 0x620c,
},
{
  .name = "D1OVL_MATRIX_COEF_1_4",
  .address = 0x6210,
},
{
  .name = "D1OVL_MATRIX_COEF_2_1",
  .address = 0x6214,
},
{
  .name = "D1OVL_MATRIX_COEF_2_2",
  .address = 0x6218,
},
{
  .name = "D1OVL_MATRIX_COEF_2_3",
  .address = 0x621c,
},
{
  .name = "D1OVL_MATRIX_COEF_2_4",
  .address = 0x6220,
},
{
  .name = "D1OVL_MATRIX_COEF_3_1",
  .address = 0x6224,
},
{
  .name = "D1OVL_MATRIX_COEF_3_2",
  .address = 0x6228,
},
{
  .name = "D1OVL_MATRIX_COEF_3_3",
  .address = 0x622c,
},
{
  .name = "D1OVL_MATRIX_COEF_3_4",
  .address = 0x6230,
},
{
  .name = "D1OVL_PWL_TRANSFORM_EN",
  .address = 0x6280,
},
{
  .name = "D1OVL_PWL_0TOF",
  .address = 0x6284,
},
{
  .name = "D1OVL_PWL_10TO1F",
  .address = 0x6288,
},
{
  .name = "D1OVL_PWL_20TO3F",
  .address = 0x628c,
},
{
  .name = "D1OVL_PWL_40TO7F",
  .address = 0x6290,
},
{
  .name = "D1OVL_PWL_80TOBF",
  .address = 0x6294,
},
{
  .name = "D1OVL_PWL_C0TOFF",
  .address = 0x6298,
},
{
  .name = "D1OVL_PWL_100TO13F",
  .address = 0x629c,
},
{
  .name = "D1OVL_PWL_140TO17F",
  .address = 0x62a0,
},
{
  .name = "D1OVL_PWL_180TO1BF",
  .address = 0x62a4,
},
{
  .name = "D1OVL_PWL_1C0TO1FF",
  .address = 0x62a8,
},
{
  .name = "D1OVL_PWL_200TO23F",
  .address = 0x62ac,
},
{
  .name = "D1OVL_PWL_240TO27F",
  .address = 0x62b0,
},
{
  .name = "D1OVL_PWL_280TO2BF",
  .address = 0x62b4,
},
{
  .name = "D1OVL_PWL_2C0TO2FF",
  .address = 0x62b8,
},
{
  .name = "D1OVL_PWL_300TO33F",
  .address = 0x62bc,
},
{
  .name = "D1OVL_PWL_340TO37F",
  .address = 0x62c0,
},
{
  .name = "D1OVL_PWL_380TO3BF",
  .address = 0x62c4,
},
{
  .name = "D1OVL_PWL_3C0TO3FF",
  .address = 0x62c8,
},
{
  .name = "D1OVL_KEY_CONTROL",
  .address = 0x6300,
},
{
  .name = "D1GRPH_ALPHA",
  .address = 0x6304,
},
{
  .name = "D1OVL_ALPHA",
  .address = 0x6308,
},
{
  .name = "D1OVL_ALPHA_CONTROL",
  .address = 0x630c,
},
{
  .name = "D1GRPH_KEY_RANGE_RED",
  .address = 0x6310,
},
{
  .name = "D1GRPH_KEY_RANGE_GREEN",
  .address = 0x6314,
},
{
  .name = "D1GRPH_KEY_RANGE_BLUE",
  .address = 0x6318,
},
{
  .name = "D1GRPH_KEY_RANGE_ALPHA",
  .address = 0x631c,
},
{
  .name = "D1OVL_KEY_RANGE_RED_CR",
  .address = 0x6320,
},
{
  .name = "D1OVL_KEY_RANGE_GREEN_Y",
  .address = 0x6324,
},
{
  .name = "D1OVL_KEY_RANGE_BLUE_CB",
  .address = 0x6328,
},
{
  .name = "D1OVL_KEY_ALPHA",
  .address = 0x632c,
},
{
  .name = "D1GRPH_COLOR_MATRIX_TRANSFORMATION_CNTL",
  .address = 0x6380,
},
{
  .name = "D1COLOR_MATRIX_COEF_1_1",
  .address = 0x6384,
},
{
  .name = "D1COLOR_MATRIX_COEF_1_2",
  .address = 0x6388,
},
{
  .name = "D1COLOR_MATRIX_COEF_1_3",
  .address = 0x638c,
},
{
  .name = "D1COLOR_MATRIX_COEF_1_4",
  .address = 0x6390,
},
{
  .name = "D1COLOR_MATRIX_COEF_2_1",
  .address = 0x6394,
},
{
  .name = "D1COLOR_MATRIX_COEF_2_2",
  .address = 0x6398,
},
{
  .name = "D1COLOR_MATRIX_COEF_2_3",
  .address = 0x639c,
},
{
  .name = "D1COLOR_MATRIX_COEF_2_4",
  .address = 0x63a0,
},
{
  .name = "D1COLOR_MATRIX_COEF_3_1",
  .address = 0x63a4,
},
{
  .name = "D1COLOR_MATRIX_COEF_3_2",
  .address = 0x63a8,
},
{
  .name = "D1COLOR_MATRIX_COEF_3_3",
  .address = 0x63ac,
},
{
  .name = "D1COLOR_MATRIX_COEF_3_4",
  .address = 0x63b0,
},
{
  .name = "D1CUR_CONTROL",
  .address = 0x6400,
},
{
  .name = "D1CUR_SURFACE_ADDRESS",
  .address = 0x6408,
},
{
  .name = "D1CUR_SIZE",
  .address = 0x6410,
},
{
  .name = "D1CUR_POSITION",
  .address = 0x6414,
},
{
  .name = "D1CUR_HOT_SPOT",
  .address = 0x6418,
},
{
  .name = "D1CUR_COLOR1",
  .address = 0x641c,
},
{
  .name = "D1CUR_COLOR2",
  .address = 0x6420,
},
{
  .name = "D1CUR_UPDATE",
  .address = 0x6424,
},
{
  .name = "D1ICON_CONTROL",
  .address = 0x6440,
},
{
  .name = "D1ICON_SURFACE_ADDRESS",
  .address = 0x6448,
},
{
  .name = "D1ICON_SIZE",
  .address = 0x6450,
},
{
  .name = "D1ICON_START_POSITION",
  .address = 0x6454,
},
{
  .name = "D1ICON_COLOR1",
  .address = 0x6458,
},
{
  .name = "D1ICON_COLOR2",
  .address = 0x645c,
},
{
  .name = "D1ICON_UPDATE",
  .address = 0x6460,
},
{
  .name = "DC_LUT_RW_SELECT",
  .address = 0x6480,
},
{
  .name = "DC_LUT_RW_MODE",
  .address = 0x6484,
},
{
  .name = "DC_LUT_RW_INDEX",
  .address = 0x6488,
},
{
  .name = "DC_LUT_SEQ_COLOR",
  .address = 0x648c,
},
{
  .name = "DC_LUT_PWL_DATA",
  .address = 0x6490,
},
{
  .name = "DC_LUT_30_COLOR",
  .address = 0x6494,
},
{
  .name = "DC_LUT_READ_PIPE_SELECT",
  .address = 0x6498,
},
{
  .name = "DC_LUT_WRITE_EN_MASK",
  .address = 0x649c,
},
{
  .name = "DC_LUT_AUTOFILL",
  .address = 0x64a0,
},
{
  .name = "DC_LUTA_CONTROL",
  .address = 0x64c0,
},
{
  .name = "DC_LUTA_BLACK_OFFSET_BLUE",
  .address = 0x64c4,
},
{
  .name = "DC_LUTA_BLACK_OFFSET_GREEN",
  .address = 0x64c8,
},
{
  .name = "DC_LUTA_BLACK_OFFSET_RED",
  .address = 0x64cc,
},
{
  .name = "DC_LUTA_WHITE_OFFSET_BLUE",
  .address = 0x64d0,
},
{
  .name = "DC_LUTA_WHITE_OFFSET_GREEN",
  .address = 0x64d4,
},
{
  .name = "DC_LUTA_WHITE_OFFSET_RED",
  .address = 0x64d8,
},
{
  .name = "D2CRTC_H_TOTAL",
  .address = 0x6800,
},
{
  .name = "D2CRTC_H_BLANK_START_END",
  .address = 0x6804,
},
{
  .name = "D2CRTC_H_SYNC_A",
  .address = 0x6808,
},
{
  .name = "D2CRTC_H_SYNC_A_CNTL",
  .address = 0x680c,
},
{
  .name = "D2CRTC_H_SYNC_B",
  .address = 0x6810,
},
{
  .name = "D2CRTC_H_SYNC_B_CNTL",
  .address = 0x6814,
},
{
  .name = "D2CRTC_V_TOTAL",
  .address = 0x6820,
},
{
  .name = "D2CRTC_V_BLANK_START_END",
  .address = 0x6824,
},
{
  .name = "D2CRTC_V_SYNC_A",
  .address = 0x6828,
},
{
  .name = "D2CRTC_V_SYNC_A_CNTL",
  .address = 0x682c,
},
{
  .name = "D2CRTC_V_SYNC_B",
  .address = 0x6830,
},
{
  .name = "D2CRTC_V_SYNC_B_CNTL",
  .address = 0x6834,
},
{
  .name = "D2CRTC_TRIGA_CNTL",
  .address = 0x6860,
},
{
  .name = "D2CRTC_TRIGA_MANUAL_TRIG",
  .address = 0x6864,
},
{
  .name = "D2CRTC_TRIGB_CNTL",
  .address = 0x6868,
},
{
  .name = "D2CRTC_TRIGB_MANUAL_TRIG",
  .address = 0x686c,
},
{
  .name = "D2CRTC_FORCE_COUNT_NOW_CNTL",
  .address = 0x6870,
},
{
  .name = "D2CRTC_FLOW_CONTROL",
  .address = 0x6874,
},
{
  .name = "D2CRTC_PIXEL_DATA_READBACK",
  .address = 0x6878,
},
{
  .name = "D2CRTC_STEREO_FORCE_NEXT_EYE",
  .address = 0x687c,
},
{
  .name = "D2CRTC_CONTROL",
  .address = 0x6880,
},
{
  .name = "D2CRTC_BLANK_CONTROL",
  .address = 0x6884,
},
{
  .name = "D2CRTC_INTERLACE_CONTROL",
  .address = 0x6888,
},
{
  .name = "D2CRTC_INTERLACE_STATUS",
  .address = 0x688c,
},
{
  .name = "D2CRTC_BLANK_DATA_COLOR",
  .address = 0x6890,
},
{
  .name = "D2CRTC_OVERSCAN_COLOR",
  .address = 0x6894,
},
{
  .name = "D2CRTC_BLACK_COLOR",
  .address = 0x6898,
},
{
  .name = "D2CRTC_STATUS",
  .address = 0x689c,
},
{
  .name = "D2CRTC_STATUS_POSITION",
  .address = 0x68a0,
},
{
  .name = "D2CRTC_STATUS_FRAME_COUNT",
  .address = 0x68a4,
},
{
  .name = "D2CRTC_STATUS_VF_COUNT",
  .address = 0x68a8,
},
{
  .name = "D2CRTC_STATUS_HV_COUNT",
  .address = 0x68ac,
},
{
  .name = "D2CRTC_COUNT_RESET",
  .address = 0x68b0,
},
{
  .name = "D2CRTC_COUNT_CONTROL",
  .address = 0x68b4,
},
{
  .name = "D2CRTC_MANUAL_FORCE_VSYNC_NEXT_LINE",
  .address = 0x68b8,
},
{
  .name = "D2CRTC_VERT_SYNC_CONTROL",
  .address = 0x68bc,
},
{
  .name = "D2CRTC_STEREO_STATUS",
  .address = 0x68c0,
},
{
  .name = "D2CRTC_STEREO_CONTROL",
  .address = 0x68c4,
},
{
  .name = "D2CRTC_SNAPSHOT_STATUS",
  .address = 0x68c8,
},
{
  .name = "D2CRTC_SNAPSHOT_CONTROL",
  .address = 0x68cc,
},
{
  .name = "D2CRTC_SNAPSHOT_POSITION",
  .address = 0x68d0,
},
{
  .name = "D2CRTC_SNAPSHOT_FRAME",
  .address = 0x68d4,
},
{
  .name = "D2CRTC_START_LINE_CONTROL",
  .address = 0x68d8,
},
{
  .name = "D2CRTC_INTERRUPT_CONTROL",
  .address = 0x68dc,
},
{
  .name = "D2MODE_MASTER_UPDATE_LOCK",
  .address = 0x68e0,
},
{
  .name = "D2MODE_MASTER_UPDATE_MODE",
  .address = 0x68e4,
},
{
  .name = "D2CRTC_UPDATE_LOCK",
  .address = 0x68e8,
},
{
  .name = "D2CRTC_DOUBLE_BUFFER_CONTROL",
  .address = 0x68ec,
},
{
  .name = "D2CRTC_VGA_PARAMETER_CAPTURE_MODE",
  .address = 0x68f0,
},
{
  .name = "D2GRPH_ENABLE",
  .address = 0x6900,
},
{
  .name = "D2GRPH_CONTROL",
  .address = 0x6904,
},
{
  .name = "D2GRPH_LUT_SEL",
  .address = 0x6908,
},
{
  .name = "D2GRPH_PRIMARY_SURFACE_ADDRESS",
  .address = 0x6910,
},
{
  .name = "D2GRPH_SECONDARY_SURFACE_ADDRESS",
  .address = 0x6918,
},
{
  .name = "D2GRPH_PITCH",
  .address = 0x6920,
},
{
  .name = "D2GRPH_SURFACE_OFFSET_X",
  .address = 0x6924,
},
{
  .name = "D2GRPH_SURFACE_OFFSET_Y",
  .address = 0x6928,
},
{
  .name = "D2GRPH_X_START",
  .address = 0x692c,
},
{
  .name = "D2GRPH_Y_START",
  .address = 0x6930,
},
{
  .name = "D2GRPH_X_END",
  .address = 0x6934,
},
{
  .name = "D2GRPH_Y_END",
  .address = 0x6938,
},
{
  .name = "D2COLOR_SPACE_CONVERT",
  .address = 0x693c,
},
{
  .name = "D2OVL_COLOR_MATRIX_TRANSFORMATION_CNTL",
  .address = 0x6940,
},
{
  .name = "D2GRPH_UPDATE",
  .address = 0x6944,
},
{
  .name = "D2GRPH_FLIP_CONTROL",
  .address = 0x6948,
},
{
  .name = "D2GRPH_SURFACE_ADDRESS_INUSE",
  .address = 0x694c,
},
{
  .name = "D2OVL_ENABLE",
  .address = 0x6980,
},
{
  .name = "D2OVL_CONTROL1",
  .address = 0x6984,
},
{
  .name = "D2OVL_CONTROL2",
  .address = 0x6988,
},
{
  .name = "D2OVL_SURFACE_ADDRESS",
  .address = 0x6990,
},
{
  .name = "D2OVL_PITCH",
  .address = 0x6998,
},
{
  .name = "D2OVL_SURFACE_OFFSET_X",
  .address = 0x699c,
},
{
  .name = "D2OVL_SURFACE_OFFSET_Y",
  .address = 0x69a0,
},
{
  .name = "D2OVL_START",
  .address = 0x69a4,
},
{
  .name = "D2OVL_END",
  .address = 0x69a8,
},
{
  .name = "D2OVL_UPDATE",
  .address = 0x69ac,
},
{
  .name = "D2OVL_SURFACE_ADDRESS_INUSE",
  .address = 0x69b0,
},
{
  .name = "D2OVL_MATRIX_TRANSFORM_EN",
  .address = 0x6a00,
},
{
  .name = "D2OVL_MATRIX_COEF_1_1",
  .address = 0x6a04,
},
{
  .name = "D2OVL_MATRIX_COEF_1_2",
  .address = 0x6a08,
},
{
  .name = "D2OVL_MATRIX_COEF_1_3",
  .address = 0x6a0c,
},
{
  .name = "D2OVL_MATRIX_COEF_1_4",
  .address = 0x6a10,
},
{
  .name = "D2OVL_MATRIX_COEF_2_1",
  .address = 0x6a14,
},
{
  .name = "D2OVL_MATRIX_COEF_2_2",
  .address = 0x6a18,
},
{
  .name = "D2OVL_MATRIX_COEF_2_3",
  .address = 0x6a1c,
},
{
  .name = "D2OVL_MATRIX_COEF_2_4",
  .address = 0x6a20,
},
{
  .name = "D2OVL_MATRIX_COEF_3_1",
  .address = 0x6a24,
},
{
  .name = "D2OVL_MATRIX_COEF_3_2",
  .address = 0x6a28,
},
{
  .name = "D2OVL_MATRIX_COEF_3_3",
  .address = 0x6a2c,
},
{
  .name = "D2OVL_MATRIX_COEF_3_4",
  .address = 0x6a30,
},
{
  .name = "D2OVL_PWL_TRANSFORM_EN",
  .address = 0x6a80,
},
{
  .name = "D2OVL_PWL_0TOF",
  .address = 0x6a84,
},
{
  .name = "D2OVL_PWL_10TO1F",
  .address = 0x6a88,
},
{
  .name = "D2OVL_PWL_20TO3F",
  .address = 0x6a8c,
},
{
  .name = "D2OVL_PWL_40TO7F",
  .address = 0x6a90,
},
{
  .name = "D2OVL_PWL_80TOBF",
  .address = 0x6a94,
},
{
  .name = "D2OVL_PWL_C0TOFF",
  .address = 0x6a98,
},
{
  .name = "D2OVL_PWL_100TO13F",
  .address = 0x6a9c,
},
{
  .name = "D2OVL_PWL_140TO17F",
  .address = 0x6aa0,
},
{
  .name = "D2OVL_PWL_180TO1BF",
  .address = 0x6aa4,
},
{
  .name = "D2OVL_PWL_1C0TO1FF",
  .address = 0x6aa8,
},
{
  .name = "D2OVL_PWL_200TO23F",
  .address = 0x6aac,
},
{
  .name = "D2OVL_PWL_240TO27F",
  .address = 0x6ab0,
},
{
  .name = "D2OVL_PWL_280TO2BF",
  .address = 0x6ab4,
},
{
  .name = "D2OVL_PWL_2C0TO2FF",
  .address = 0x6ab8,
},
{
  .name = "D2OVL_PWL_300TO33F",
  .address = 0x6abc,
},
{
  .name = "D2OVL_PWL_340TO37F",
  .address = 0x6ac0,
},
{
  .name = "D2OVL_PWL_380TO3BF",
  .address = 0x6ac4,
},
{
  .name = "D2OVL_PWL_3C0TO3FF",
  .address = 0x6ac8,
},
{
  .name = "D2OVL_KEY_CONTROL",
  .address = 0x6b00,
},
{
  .name = "D2GRPH_ALPHA",
  .address = 0x6b04,
},
{
  .name = "D2OVL_ALPHA",
  .address = 0x6b08,
},
{
  .name = "D2OVL_ALPHA_CONTROL",
  .address = 0x6b0c,
},
{
  .name = "D2GRPH_KEY_RANGE_RED",
  .address = 0x6b10,
},
{
  .name = "D2GRPH_KEY_RANGE_GREEN",
  .address = 0x6b14,
},
{
  .name = "D2GRPH_KEY_RANGE_BLUE",
  .address = 0x6b18,
},
{
  .name = "D2GRPH_KEY_RANGE_ALPHA",
  .address = 0x6b1c,
},
{
  .name = "D2OVL_KEY_RANGE_RED_CR",
  .address = 0x6b20,
},
{
  .name = "D2OVL_KEY_RANGE_GREEN_Y",
  .address = 0x6b24,
},
{
  .name = "D2OVL_KEY_RANGE_BLUE_CB",
  .address = 0x6b28,
},
{
  .name = "D2OVL_KEY_ALPHA",
  .address = 0x6b2c,
},
{
  .name = "D2GRPH_COLOR_MATRIX_TRANSFORMATION_CNTL",
  .address = 0x6b80,
},
{
  .name = "D2COLOR_MATRIX_COEF_1_1",
  .address = 0x6b84,
},
{
  .name = "D2COLOR_MATRIX_COEF_1_2",
  .address = 0x6b88,
},
{
  .name = "D2COLOR_MATRIX_COEF_1_3",
  .address = 0x6b8c,
},
{
  .name = "D2COLOR_MATRIX_COEF_1_4",
  .address = 0x6b90,
},
{
  .name = "D2COLOR_MATRIX_COEF_2_1",
  .address = 0x6b94,
},
{
  .name = "D2COLOR_MATRIX_COEF_2_2",
  .address = 0x6b98,
},
{
  .name = "D2COLOR_MATRIX_COEF_2_3",
  .address = 0x6b9c,
},
{
  .name = "D2COLOR_MATRIX_COEF_2_4",
  .address = 0x6ba0,
},
{
  .name = "D2COLOR_MATRIX_COEF_3_1",
  .address = 0x6ba4,
},
{
  .name = "D2COLOR_MATRIX_COEF_3_2",
  .address = 0x6ba8,
},
{
  .name = "D2COLOR_MATRIX_COEF_3_3",
  .address = 0x6bac,
},
{
  .name = "D2COLOR_MATRIX_COEF_3_4",
  .address = 0x6bb0,
},
{
  .name = "D2CUR_CONTROL",
  .address = 0x6c00,
},
{
  .name = "D2CUR_SURFACE_ADDRESS",
  .address = 0x6c08,
},
{
  .name = "D2CUR_SIZE",
  .address = 0x6c10,
},
{
  .name = "D2CUR_POSITION",
  .address = 0x6c14,
},
{
  .name = "D2CUR_HOT_SPOT",
  .address = 0x6c18,
},
{
  .name = "D2CUR_COLOR1",
  .address = 0x6c1c,
},
{
  .name = "D2CUR_COLOR2",
  .address = 0x6c20,
},
{
  .name = "D2CUR_UPDATE",
  .address = 0x6c24,
},
{
  .name = "D2ICON_CONTROL",
  .address = 0x6c40,
},
{
  .name = "D2ICON_SURFACE_ADDRESS",
  .address = 0x6c48,
},
{
  .name = "D2ICON_SIZE",
  .address = 0x6c50,
},
{
  .name = "D2ICON_START_POSITION",
  .address = 0x6c54,
},
{
  .name = "D2ICON_COLOR1",
  .address = 0x6c58,
},
{
  .name = "D2ICON_COLOR2",
  .address = 0x6c5c,
},
{
  .name = "D2ICON_UPDATE",
  .address = 0x6c60,
},
{
  .name = "DCP_CRC_CONTROL",
  .address = 0x6c80,
},
{
  .name = "DCP_CRC_MASK",
  .address = 0x6c84,
},
{
  .name = "DCP_CRC_P0_CURRENT",
  .address = 0x6c88,
},
{
  .name = "DCP_CRC_P1_CURRENT",
  .address = 0x6c8c,
},
{
  .name = "DCP_CRC_P0_LAST",
  .address = 0x6c90,
},
{
  .name = "DCP_CRC_P1_LAST",
  .address = 0x6c94,
},
{
  .name = "DMIF_CONTROL",
  .address = 0x6cb0,
},
{
  .name = "DMIF_STATUS",
  .address = 0x6cb4,
},
{
  .name = "MCIF_CONTROL",
  .address = 0x6cb8,
},
{
  .name = "DCP_LB_DATA_GAP_BETWEEN_CHUNK",
  .address = 0x6cbc,
},
{
  .name = "DC_LUTB_CONTROL",
  .address = 0x6cc0,
},
{
  .name = "DC_LUTB_BLACK_OFFSET_BLUE",
  .address = 0x6cc4,
},
{
  .name = "DC_LUTB_BLACK_OFFSET_GREEN",
  .address = 0x6cc8,
},
{
  .name = "DC_LUTB_BLACK_OFFSET_RED",
  .address = 0x6ccc,
},
{
  .name = "DC_LUTB_WHITE_OFFSET_BLUE",
  .address = 0x6cd0,
},
{
  .name = "DC_LUTB_WHITE_OFFSET_GREEN",
  .address = 0x6cd4,
},
{
  .name = "DC_LUTB_WHITE_OFFSET_RED",
  .address = 0x6cd8,
},
{
  .name = "DACA_ENABLE",
  .address = 0x7800,
},
{
  .name = "DACA_SOURCE_SELECT",
  .address = 0x7804,
},
{
  .name = "DACA_CRC_EN",
  .address = 0x7808,
},
{
  .name = "DACA_CRC_CONTROL",
  .address = 0x780c,
},
{
  .name = "DACA_CRC_SIG_RGB_MASK",
  .address = 0x7810,
},
{
  .name = "DACA_CRC_SIG_CONTROL_MASK",
  .address = 0x7814,
},
{
  .name = "DACA_CRC_SIG_RGB",
  .address = 0x7818,
},
{
  .name = "DACA_CRC_SIG_CONTROL",
  .address = 0x781c,
},
{
  .name = "DACA_SYNC_TRISTATE_CONTROL",
  .address = 0x7820,
},
{
  .name = "DACA_SYNC_SELECT",
  .address = 0x7824,
},
{
  .name = "DACA_AUTODETECT_CONTROL",
  .address = 0x7828,
},
{
  .name = "DACA_AUTODETECT_CONTROL2",
  .address = 0x782c,
},
{
  .name = "DACA_AUTODETECT_STATUS",
  .address = 0x7834,
},
{
  .name = "DACA_AUTODETECT_INT_CONTROL",
  .address = 0x7838,
},
{
  .name = "DACA_FORCE_OUTPUT_CNTL",
  .address = 0x783c,
},
{
  .name = "DACA_FORCE_DATA",
  .address = 0x7840,
},
{
  .name = "DACA_POWERDOWN",
  .address = 0x7850,
},
{
  .name = "DACA_CONTROL1",
  .address = 0x7854,
},
{
  .name = "DACA_CONTROL2",
  .address = 0x7858,
},
{
  .name = "DACA_COMPARATOR_ENABLE",
  .address = 0x785c,
},
{
  .name = "DACA_COMPARATOR_OUTPUT",
  .address = 0x7860,
},
{
  .name = "DACA_TEST_ENABLE",
  .address = 0x7864,
},
{
  .name = "DACA_PWR_CNTL",
  .address = 0x7868,
},
{
  .name = "TMDSA_CNTL",
  .address = 0x7880,
},
{
  .name = "TMDSA_SOURCE_SELECT",
  .address = 0x7884,
},
{
  .name = "TMDSA_COLOR_FORMAT",
  .address = 0x7888,
},
{
  .name = "TMDSA_FORCE_OUTPUT_CNTL",
  .address = 0x788c,
},
{
  .name = "TMDSA_FORCE_DATA",
  .address = 0x7890,
},
{
  .name = "TMDSA_BIT_DEPTH_CONTROL",
  .address = 0x7894,
},
{
  .name = "TMDSA_CONTROL_CHAR",
  .address = 0x7898,
},
{
  .name = "TMDSA_CONTROL0_FEEDBACK",
  .address = 0x789c,
},
{
  .name = "TMDSA_STEREOSYNC_CTL_SEL",
  .address = 0x78a0,
},
{
  .name = "TMDSA_SYNC_CHAR_PATTERN_SEL",
  .address = 0x78a4,
},
{
  .name = "TMDSA_SYNC_CHAR_PATTERN_0_1",
  .address = 0x78a8,
},
{
  .name = "TMDSA_SYNC_CHAR_PATTERN_2_3",
  .address = 0x78ac,
},
{
  .name = "TMDSA_CRC_CNTL",
  .address = 0x78b0,
},
{
  .name = "TMDSA_CRC_SIG_MASK",
  .address = 0x78b4,
},
{
  .name = "TMDSA_CRC_SIG_RGB",
  .address = 0x78b8,
},
{
  .name = "TMDSA_2ND_CRC_RESULT",
  .address = 0x78bc,
},
{
  .name = "TMDSA_TEST_PATTERN",
  .address = 0x78c0,
},
{
  .name = "TMDSA_RANDOM_PATTERN_SEED",
  .address = 0x78c4,
},
{
  .name = "TMDSA_DEBUG",
  .address = 0x78c8,
},
{
  .name = "TMDSA_CTL_BITS",
  .address = 0x78cc,
},
{
  .name = "TMDSA_DCBALANCER_CONTROL",
  .address = 0x78d0,
},
{
  .name = "TMDSA_RED_BLUE_SWITCH",
  .address = 0x78d4,
},
{
  .name = "TMDSA_DATA_SYNCHRONIZATION",
  .address = 0x78d8,
},
{
  .name = "TMDSA_CTL0_1_GEN_CNTL",
  .address = 0x78dc,
},
{
  .name = "TMDSA_CTL2_3_GEN_CNTL",
  .address = 0x78e0,
},
{
  .name = "TMDSA_TRANSMITTER_ENABLE",
  .address = 0x7904,
},
{
  .name = "TMDSA_LOAD_DETECT",
  .address = 0x7908,
},
{
  .name = "TMDSA_MACRO_CONTROL",
  .address = 0x790c,
},
{
  .name = "TMDSA_TRANSMITTER_CONTROL",
  .address = 0x7910,
},
{
  .name = "TMDSA_REG_TEST_OUTPUT",
  .address = 0x7914,
},
{
  .name = "TMDSA_TRANSMITTER_DEBUG",
  .address = 0x7918,
},
{
  .name = "DVOA_ENABLE",
  .address = 0x7980,
},
{
  .name = "DVOA_SOURCE_SELECT",
  .address = 0x7984,
},
{
  .name = "DVOA_BIT_DEPTH_CONTROL",
  .address = 0x7988,
},
{
  .name = "DVOA_OUTPUT",
  .address = 0x798c,
},
{
  .name = "DVOA_CONTROL",
  .address = 0x7990,
},
{
  .name = "DVOA_CRC_EN",
  .address = 0x7994,
},
{
  .name = "DVOA_CRC_CONTROL",
  .address = 0x7998,
},
{
  .name = "DVOA_CRC_SIG_MASK1",
  .address = 0x799c,
},
{
  .name = "DVOA_CRC_SIG_MASK2",
  .address = 0x79a0,
},
{
  .name = "DVOA_CRC_SIG_RESULT1",
  .address = 0x79a4,
},
{
  .name = "DVOA_CRC_SIG_RESULT2",
  .address = 0x79a8,
},
{
  .name = "DVOA_CRC2_SIG_MASK",
  .address = 0x79ac,
},
{
  .name = "DVOA_CRC2_SIG_RESULT",
  .address = 0x79b0,
},
{
  .name = "DVOA_STRENGTH_CONTROL",
  .address = 0x79b4,
},
{
  .name = "DVOA_FORCE_OUTPUT_CNTL",
  .address = 0x79b8,
},
{
  .name = "DVOA_FORCE_DATA",
  .address = 0x79bc,
},
{
  .name = "DACB_ENABLE",
  .address = 0x7a00,
},
{
  .name = "DACB_SOURCE_SELECT",
  .address = 0x7a04,
},
{
  .name = "DACB_CRC_EN",
  .address = 0x7a08,
},
{
  .name = "DACB_CRC_CONTROL",
  .address = 0x7a0c,
},
{
  .name = "DACB_CRC_SIG_RGB_MASK",
  .address = 0x7a10,
},
{
  .name = "DACB_CRC_SIG_CONTROL_MASK",
  .address = 0x7a14,
},
{
  .name = "DACB_CRC_SIG_RGB",
  .address = 0x7a18,
},
{
  .name = "DACB_CRC_SIG_CONTROL",
  .address = 0x7a1c,
},
{
  .name = "DACB_SYNC_TRISTATE_CONTROL",
  .address = 0x7a20,
},
{
  .name = "DACB_SYNC_SELECT",
  .address = 0x7a24,
},
{
  .name = "DACB_AUTODETECT_CONTROL",
  .address = 0x7a28,
},
{
  .name = "DACB_AUTODETECT_CONTROL2",
  .address = 0x7a2c,
},
{
  .name = "DACB_AUTODETECT_STATUS",
  .address = 0x7a34,
},
{
  .name = "DACB_AUTODETECT_INT_CONTROL",
  .address = 0x7a38,
},
{
  .name = "DACB_FORCE_OUTPUT_CNTL",
  .address = 0x7a3c,
},
{
  .name = "DACB_FORCE_DATA",
  .address = 0x7a40,
},
{
  .name = "DACB_POWERDOWN",
  .address = 0x7a50,
},
{
  .name = "DACB_CONTROL1",
  .address = 0x7a54,
},
{
  .name = "DACB_CONTROL2",
  .address = 0x7a58,
},
{
  .name = "DACB_COMPARATOR_ENABLE",
  .address = 0x7a5c,
},
{
  .name = "DACB_COMPARATOR_OUTPUT",
  .address = 0x7a60,
},
{
  .name = "DACB_TEST_ENABLE",
  .address = 0x7a64,
},
{
  .name = "DACB_PWR_CNTL",
  .address = 0x7a68,
},
{
  .name = "LVTMA_CNTL",
  .address = 0x7a80,
},
{
  .name = "LVTMA_SOURCE_SELECT",
  .address = 0x7a84,
},
{
  .name = "LVTMA_COLOR_FORMAT",
  .address = 0x7a88,
},
{
  .name = "LVTMA_FORCE_OUTPUT_CNTL",
  .address = 0x7a8c,
},
{
  .name = "LVTMA_FORCE_DATA",
  .address = 0x7a90,
},
{
  .name = "LVTMA_BIT_DEPTH_CONTROL",
  .address = 0x7a94,
},
{
  .name = "LVTMA_CONTROL_CHAR",
  .address = 0x7a98,
},
{
  .name = "LVTMA_CONTROL0_FEEDBACK",
  .address = 0x7a9c,
},
{
  .name = "LVTMA_STEREOSYNC_CTL_SEL",
  .address = 0x7aa0,
},
{
  .name = "LVTMA_SYNC_CHAR_PATTERN_SEL",
  .address = 0x7aa4,
},
{
  .name = "LVTMA_SYNC_CHAR_PATTERN_0_1",
  .address = 0x7aa8,
},
{
  .name = "LVTMA_SYNC_CHAR_PATTERN_2_3",
  .address = 0x7aac,
},
{
  .name = "LVTMA_CRC_CNTL",
  .address = 0x7ab0,
},
{
  .name = "LVTMA_CRC_SIG_MASK",
  .address = 0x7ab4,
},
{
  .name = "LVTMA_CRC_SIG_RGB",
  .address = 0x7ab8,
},
{
  .name = "LVTMA_2ND_CRC_RESULT",
  .address = 0x7abc,
},
{
  .name = "LVTMA_TEST_PATTERN",
  .address = 0x7ac0,
},
{
  .name = "LVTMA_RANDOM_PATTERN_SEED",
  .address = 0x7ac4,
},
{
  .name = "LVTMA_DEBUG",
  .address = 0x7ac8,
},
{
  .name = "LVTMA_CTL_BITS",
  .address = 0x7acc,
},
{
  .name = "LVTMA_DCBALANCER_CONTROL",
  .address = 0x7ad0,
},
{
  .name = "LVTMA_RED_BLUE_SWITCH",
  .address = 0x7ad4,
},
{
  .name = "LVTMA_DATA_SYNCHRONIZATION",
  .address = 0x7ad8,
},
{
  .name = "LVTMA_CTL0_1_GEN_CNTL",
  .address = 0x7adc,
},
{
  .name = "LVTMA_CTL2_3_GEN_CNTL",
  .address = 0x7ae0,
},
{
  .name = "LVTMA_PWRSEQ_REF_DIV",
  .address = 0x7ae4,
},
{
  .name = "LVTMA_PWRSEQ_DELAY1",
  .address = 0x7ae8,
},
{
  .name = "LVTMA_PWRSEQ_DELAY2",
  .address = 0x7aec,
},
{
  .name = "LVTMA_PWRSEQ_CNTL",
  .address = 0x7af0,
},
{
  .name = "LVTMA_PWRSEQ_STATE",
  .address = 0x7af4,
},
{
  .name = "LVTMA_BL_MOD_CNTL",
  .address = 0x7af8,
},
{
  .name = "LVTMA_LVDS_DATA_CNTL",
  .address = 0x7afc,
},
{
  .name = "LVTMA_MODE",
  .address = 0x7b00,
},
{
  .name = "LVTMA_TRANSMITTER_ENABLE",
  .address = 0x7b04,
},
{
  .name = "LVTMA_LOAD_DETECT",
  .address = 0x7b08,
},
{
  .name = "LVTMA_MACRO_CONTROL",
  .address = 0x7b0c,
},
{
  .name = "LVTMA_TRANSMITTER_CONTROL",
  .address = 0x7b10,
},
{
  .name = "LVTMA_REG_TEST_OUTPUT",
  .address = 0x7b14,
},
{
  .name = "LVTMA_TRANSMITTER_DEBUG",
  .address = 0x7b18,
},
{
  .name = "DC_HOT_PLUG_DETECT1_CONTROL",
  .address = 0x7d00,
},
{
  .name = "DC_HOT_PLUG_DETECT1_INT_STATUS",
  .address = 0x7d04,
},
{
  .name = "DC_HOT_PLUG_DETECT1_INT_CONTROL",
  .address = 0x7d08,
},
{
  .name = "DC_HOT_PLUG_DETECT2_CONTROL",
  .address = 0x7d10,
},
{
  .name = "DC_HOT_PLUG_DETECT2_INT_STATUS",
  .address = 0x7d14,
},
{
  .name = "DC_HOT_PLUG_DETECT2_INT_CONTROL",
  .address = 0x7d18,
},
{
  .name = "DC_HOT_PLUG_DETECT_CLOCK_CONTROL",
  .address = 0x7d20,
},
{
  .name = "DC_I2C_STATUS1",
  .address = 0x7d30,
},
{
  .name = "DC_I2C_RESET",
  .address = 0x7d34,
},
{
  .name = "DC_I2C_CONTROL1",
  .address = 0x7d38,
},
{
  .name = "DC_I2C_CONTROL2",
  .address = 0x7d3c,
},
{
  .name = "DC_I2C_CONTROL3",
  .address = 0x7d40,
},
{
  .name = "DC_I2C_DATA",
  .address = 0x7d44,
},
{
  .name = "DC_I2C_INTERRUPT_CONTROL",
  .address = 0x7d48,
},
{
  .name = "DC_I2C_ARBITRATION",
  .address = 0x7d50,
},
{
  .name = "DC_GENERICA",
  .address = 0x7dc0,
},
{
  .name = "DC_GENERICB",
  .address = 0x7dc4,
},
{
  .name = "DC_PAD_EXTERN_SIG",
  .address = 0x7dcc,
},
{
  .name = "DC_REF_CLK_CNTL",
  .address = 0x7dd4,
},
{
  .name = "DC_GPIO_GENERIC_MASK",
  .address = 0x7de0,
},
{
  .name = "DC_GPIO_GENERIC_A",
  .address = 0x7de4,
},
{
  .name = "DC_GPIO_GENERIC_EN",
  .address = 0x7de8,
},
{
  .name = "DC_GPIO_GENERIC_Y",
  .address = 0x7dec,
},
{
  .name = "DC_GPIO_VIP_DEBUG",
  .address = 0x7e2c,
},
{
  .name = "DC_GPIO_DVODATA_MASK",
  .address = 0x7e30,
},
{
  .name = "DC_GPIO_DVODATA_A",
  .address = 0x7e34,
},
{
  .name = "DC_GPIO_DVODATA_EN",
  .address = 0x7e38,
},
{
  .name = "DC_GPIO_DVODATA_Y",
  .address = 0x7e3c,
},
{
  .name = "DC_GPIO_DDC1_MASK",
  .address = 0x7e40,
},
{
  .name = "DC_GPIO_DDC1_A",
  .address = 0x7e44,
},
{
  .name = "DC_GPIO_DDC1_EN",
  .address = 0x7e48,
},
{
  .name = "DC_GPIO_DDC1_Y",
  .address = 0x7e4c,
},
{
  .name = "DC_GPIO_DDC2_MASK",
  .address = 0x7e50,
},
{
  .name = "DC_GPIO_DDC2_A",
  .address = 0x7e54,
},
{
  .name = "DC_GPIO_DDC2_EN",
  .address = 0x7e58,
},
{
  .name = "DC_GPIO_DDC2_Y",
  .address = 0x7e5c,
},
{
  .name = "DC_GPIO_DDC3_MASK",
  .address = 0x7e60,
},
{
  .name = "DC_GPIO_DDC3_A",
  .address = 0x7e64,
},
{
  .name = "DC_GPIO_DDC3_EN",
  .address = 0x7e68,
},
{
  .name = "DC_GPIO_DDC3_Y",
  .address = 0x7e6c,
},
{
  .name = "DC_GPIO_SYNCA_MASK",
  .address = 0x7e70,
},
{
  .name = "DC_GPIO_SYNCA_A",
  .address = 0x7e74,
},
{
  .name = "DC_GPIO_SYNCA_EN",
  .address = 0x7e78,
},
{
  .name = "DC_GPIO_SYNCA_Y",
  .address = 0x7e7c,
},
{
  .name = "DC_GPIO_SYNCB_MASK",
  .address = 0x7e80,
},
{
  .name = "DC_GPIO_SYNCB_A",
  .address = 0x7e84,
},
{
  .name = "DC_GPIO_SYNCB_EN",
  .address = 0x7e88,
},
{
  .name = "DC_GPIO_SYNCB_Y",
  .address = 0x7e8c,
},
{
  .name = "DC_GPIO_HPD_MASK",
  .address = 0x7e90,
},
{
  .name = "DC_GPIO_HPD_A",
  .address = 0x7e94,
},
{
  .name = "DC_GPIO_HPD_EN",
  .address = 0x7e98,
},
{
  .name = "DC_GPIO_HPD_Y",
  .address = 0x7e9c,
},
{
  .name = "DC_GPIO_PWRSEQ_MASK",
  .address = 0x7ea0,
},
{
  .name = "DC_GPIO_PWRSEQ_A",
  .address = 0x7ea4,
},
{
  .name = "DC_GPIO_PWRSEQ_EN",
  .address = 0x7ea8,
},
{
  .name = "DC_GPIO_PWRSEQ_Y",
  .address = 0x7eac,
},
{
  .name = "CAPTURE_START_STATUS",
  .address = 0x7ed0,
},
{
  .name = "DC_GPIO_PAD_STRENGTH_1",
  .address = 0x7ed4,
},
{
  .name = "DC_GPIO_PAD_STRENGTH_2",
  .address = 0x7ed8,
},
{
  .name = "DISP_INTERRUPT_STATUS",
  .address = 0x7edc,
},
{
  .name = "DOUT_POWER_MANAGEMENT_CNTL",
  .address = 0x7ee0,
},
{
  .name = "DISP_TIMER_CONTROL",
  .address = 0x7ef0,
},
{
  .name = "DO_PERFCOUNTER0_SELECT",
  .address = 0x7f00,
},
{
  .name = "DO_PERFCOUNTER0_HI",
  .address = 0x7f04,
},
{
  .name = "DO_PERFCOUNTER0_LOW",
  .address = 0x7f08,
},
{
  .name = "DO_PERFCOUNTER1_SELECT",
  .address = 0x7f0c,
},
{
  .name = "DO_PERFCOUNTER1_HI",
  .address = 0x7f10,
},
{
  .name = "DO_PERFCOUNTER1_LOW",
  .address = 0x7f14,
},
{
  .name = "DCO_PERFMON_CNTL_R",
  .address = 0x7f18,
},
{
  .name = "CRTC_EXT_CNTL",
  .address = 0xe054,
},
