{
  .name = "MC_IND_INDEX",
  .address = 0x70,
},
{
  .name = "MC_IND_DATA",
  .address = 0x74,
},
{
  .name = "MC_STATUS",
  .address = 0x0,
},
{
  .name = "MC_ARB_MIN",
  .address = 0x10,
},
{
  .name = "MC_PT0_CNTL",
  .address = 0x100,
},
{
  .name = "MC_PT0_CONTEXT0_CNTL",
  .address = 0x102,
},
{
  .name = "MC_PT0_CONTEXT1_CNTL",
  .address = 0x103,
},
{
  .name = "MC_PT0_CONTEXT2_CNTL",
  .address = 0x104,
},
{
  .name = "MC_PT0_CONTEXT3_CNTL",
  .address = 0x105,
},
{
  .name = "MC_PT0_CONTEXT4_CNTL",
  .address = 0x106,
},
{
  .name = "MC_PT0_CONTEXT5_CNTL",
  .address = 0x107,
},
{
  .name = "MC_PT0_CONTEXT6_CNTL",
  .address = 0x108,
},
{
  .name = "MC_PT0_CONTEXT7_CNTL",
  .address = 0x109,
},
{
  .name = "MC_PT0_SYSTEM_APERTURE_LOW_ADDR",
  .address = 0x112,
},
{
  .name = "MC_PT0_SYSTEM_APERTURE_HIGH_ADDR",
  .address = 0x114,
},
{
  .name = "MC_PT0_SURFACE_PROBE",
  .address = 0x116,
},
{
  .name = "MC_PT0_SURFACE_PROBE_FAULT_STATUS",
  .address = 0x118,
},
{
  .name = "MC_PT0_PROTECTION_FAULT_STATUS",
  .address = 0x11a,
},
{
  .name = "MC_PT0_CONTEXT0_DEFAULT_READ_ADDR",
  .address = 0x11c,
},
{
  .name = "MC_PT0_CONTEXT1_DEFAULT_READ_ADDR",
  .address = 0x11d,
},
{
  .name = "MC_PT0_CONTEXT2_DEFAULT_READ_ADDR",
  .address = 0x11e,
},
{
  .name = "MC_PT0_CONTEXT3_DEFAULT_READ_ADDR",
  .address = 0x11f,
},
{
  .name = "MC_ARB_TIMERS",
  .address = 0x12,
},
{
  .name = "MC_PT0_CONTEXT4_DEFAULT_READ_ADDR",
  .address = 0x120,
},
{
  .name = "MC_PT0_CONTEXT5_DEFAULT_READ_ADDR",
  .address = 0x121,
},
{
  .name = "MC_PT0_CONTEXT6_DEFAULT_READ_ADDR",
  .address = 0x122,
},
{
  .name = "MC_PT0_CONTEXT7_DEFAULT_READ_ADDR",
  .address = 0x123,
},
{
  .name = "MC_PT0_CONTEXT0_FLAT_BASE_ADDR",
  .address = 0x12c,
},
{
  .name = "MC_PT0_CONTEXT1_FLAT_BASE_ADDR",
  .address = 0x12d,
},
{
  .name = "MC_PT0_CONTEXT2_FLAT_BASE_ADDR",
  .address = 0x12e,
},
{
  .name = "MC_PT0_CONTEXT3_FLAT_BASE_ADDR",
  .address = 0x12f,
},
{
  .name = "MC_ARB_DRAM_PENALTIES",
  .address = 0x13,
},
{
  .name = "MC_PT0_CONTEXT4_FLAT_BASE_ADDR",
  .address = 0x130,
},
{
  .name = "MC_PT0_CONTEXT5_FLAT_BASE_ADDR",
  .address = 0x131,
},
{
  .name = "MC_PT0_CONTEXT6_FLAT_BASE_ADDR",
  .address = 0x132,
},
{
  .name = "MC_PT0_CONTEXT7_FLAT_BASE_ADDR",
  .address = 0x133,
},
{
  .name = "MC_PT0_CONTEXT0_FLAT_START_ADDR",
  .address = 0x13c,
},
{
  .name = "MC_PT0_CONTEXT1_FLAT_START_ADDR",
  .address = 0x13d,
},
{
  .name = "MC_PT0_CONTEXT2_FLAT_START_ADDR",
  .address = 0x13e,
},
{
  .name = "MC_PT0_CONTEXT3_FLAT_START_ADDR",
  .address = 0x13f,
},
{
  .name = "MC_ARB_DRAM_PENALTIES2",
  .address = 0x14,
},
{
  .name = "MC_PT0_CONTEXT4_FLAT_START_ADDR",
  .address = 0x140,
},
{
  .name = "MC_PT0_CONTEXT5_FLAT_START_ADDR",
  .address = 0x141,
},
{
  .name = "MC_PT0_CONTEXT6_FLAT_START_ADDR",
  .address = 0x142,
},
{
  .name = "MC_PT0_CONTEXT7_FLAT_START_ADDR",
  .address = 0x143,
},
{
  .name = "MC_PT0_CONTEXT0_FLAT_END_ADDR",
  .address = 0x14c,
},
{
  .name = "MC_PT0_CONTEXT1_FLAT_END_ADDR",
  .address = 0x14d,
},
{
  .name = "MC_PT0_CONTEXT2_FLAT_END_ADDR",
  .address = 0x14e,
},
{
  .name = "MC_PT0_CONTEXT3_FLAT_END_ADDR",
  .address = 0x14f,
},
{
  .name = "MC_ARB_DRAM_PENALTIES3",
  .address = 0x15,
},
{
  .name = "MC_PT0_CONTEXT4_FLAT_END_ADDR",
  .address = 0x150,
},
{
  .name = "MC_PT0_CONTEXT5_FLAT_END_ADDR",
  .address = 0x151,
},
{
  .name = "MC_PT0_CONTEXT6_FLAT_END_ADDR",
  .address = 0x152,
},
{
  .name = "MC_PT0_CONTEXT7_FLAT_END_ADDR",
  .address = 0x153,
},
{
  .name = "MC_PT0_CONTEXT0_MULTI_LEVEL_BASE_ADDR",
  .address = 0x15c,
},
{
  .name = "MC_PT0_CONTEXT1_MULTI_LEVEL_BASE_ADDR",
  .address = 0x15d,
},
{
  .name = "MC_PT0_CONTEXT2_MULTI_LEVEL_BASE_ADDR",
  .address = 0x15e,
},
{
  .name = "MC_PT0_CONTEXT3_MULTI_LEVEL_BASE_ADDR",
  .address = 0x15f,
},
{
  .name = "MC_ARB_RATIO_CLK_SEQ",
  .address = 0x16,
},
{
  .name = "MC_PT0_CONTEXT4_MULTI_LEVEL_BASE_ADDR",
  .address = 0x160,
},
{
  .name = "MC_PT0_CONTEXT5_MULTI_LEVEL_BASE_ADDR",
  .address = 0x161,
},
{
  .name = "MC_PT0_CONTEXT6_MULTI_LEVEL_BASE_ADDR",
  .address = 0x162,
},
{
  .name = "MC_PT0_CONTEXT7_MULTI_LEVEL_BASE_ADDR",
  .address = 0x163,
},
{
  .name = "MC_PT0_CLIENT0_CNTL",
  .address = 0x16c,
},
{
  .name = "MC_PT0_CLIENT1_CNTL",
  .address = 0x16d,
},
{
  .name = "MC_PT0_CLIENT2_CNTL",
  .address = 0x16e,
},
{
  .name = "MC_PT0_CLIENT3_CNTL",
  .address = 0x16f,
},
{
  .name = "MC_ARB_RDWR_SWITCH",
  .address = 0x17,
},
{
  .name = "MC_PT0_CLIENT4_CNTL",
  .address = 0x170,
},
{
  .name = "MC_PT0_CLIENT5_CNTL",
  .address = 0x171,
},
{
  .name = "MC_PT0_CLIENT6_CNTL",
  .address = 0x172,
},
{
  .name = "MC_PT0_CLIENT7_CNTL",
  .address = 0x173,
},
{
  .name = "MC_PT0_CLIENT8_CNTL",
  .address = 0x174,
},
{
  .name = "MC_PT0_CLIENT9_CNTL",
  .address = 0x175,
},
{
  .name = "MC_PT0_CLIENT10_CNTL",
  .address = 0x176,
},
{
  .name = "MC_PT0_CLIENT11_CNTL",
  .address = 0x177,
},
{
  .name = "MC_PT0_CLIENT12_CNTL",
  .address = 0x178,
},
{
  .name = "MC_PT0_CLIENT13_CNTL",
  .address = 0x179,
},
{
  .name = "MC_PT0_CLIENT14_CNTL",
  .address = 0x17a,
},
{
  .name = "MC_PT0_CLIENT15_CNTL",
  .address = 0x17b,
},
{
  .name = "MC_PT0_CLIENT16_CNTL",
  .address = 0x17c,
},
{
  .name = "MC_SW_CNTL",
  .address = 0x18,
},
{
  .name = "MC_TIMING_CNTL_2",
  .address = 0x3,
},
{
  .name = "MC_WRITE_AGE1",
  .address = 0x37,
},
{
  .name = "MC_WRITE_AGE2",
  .address = 0x38,
},
{
  .name = "MC_FB_LOCATION",
  .address = 0x4,
},
{
  .name = "MC_AGP_LOCATION",
  .address = 0x5,
},
{
  .name = "AGP_BASE",
  .address = 0x6,
},
{
  .name = "MC_SEQ_DRAM",
  .address = 0x60,
},
{
  .name = "MC_SEQ_RAS_TIMING",
  .address = 0x61,
},
{
  .name = "MC_SEQ_CAS_TIMING",
  .address = 0x62,
},
{
  .name = "MC_SEQ_MISC_TIMING",
  .address = 0x63,
},
{
  .name = "MC_SEQ_RD_CTL_I0",
  .address = 0x64,
},
{
  .name = "MC_SEQ_RD_CTL_I1",
  .address = 0x65,
},
{
  .name = "MC_SEQ_WR_CTL_I0",
  .address = 0x66,
},
{
  .name = "MC_SEQ_WR_CTL_I1",
  .address = 0x67,
},
{
  .name = "MC_SEQ_IO_CTL_I0",
  .address = 0x68,
},
{
  .name = "MC_SEQ_IO_CTL_I1",
  .address = 0x69,
},
{
  .name = "MC_SEQ_NPL_CTL_I0",
  .address = 0x6a,
},
{
  .name = "MC_SEQ_NPL_CTL_I1",
  .address = 0x6b,
},
{
  .name = "MC_SEQ_CK_PAD_CNTL_I0",
  .address = 0x6c,
},
{
  .name = "MC_SEQ_CK_PAD_CNTL_I1",
  .address = 0x6d,
},
{
  .name = "MC_SEQ_CMD_PAD_CNTL_I0",
  .address = 0x6e,
},
{
  .name = "MC_SEQ_CMD_PAD_CNTL_I1",
  .address = 0x6f,
},
{
  .name = "AGP_BASE_2",
  .address = 0x7,
},
{
  .name = "MC_SEQ_DQ_PAD_CNTL_I0",
  .address = 0x70,
},
{
  .name = "MC_SEQ_DQ_PAD_CNTL_I1",
  .address = 0x71,
},
{
  .name = "MC_SEQ_QS_PAD_CNTL_I0",
  .address = 0x72,
},
{
  .name = "MC_SEQ_QS_PAD_CNTL_I1",
  .address = 0x73,
},
{
  .name = "MC_SEQ_A_PAD_CNTL_I0",
  .address = 0x74,
},
{
  .name = "MC_SEQ_A_PAD_CNTL_I1",
  .address = 0x75,
},
{
  .name = "MC_SEQ_CMD",
  .address = 0x76,
},
{
  .name = "MC_SEQ_STATUS",
  .address = 0x77,
},
{
  .name = "MC_CNTL0",
  .address = 0x8,
},
{
  .name = "MC_IO_PAD_CNTL_I0",
  .address = 0x80,
},
{
  .name = "MC_IO_PAD_CNTL_I1",
  .address = 0x81,
},
{
  .name = "MC_IO_PAD_CNTL",
  .address = 0x82,
},
{
  .name = "MC_IO_RD_DQ_CNTL_I0",
  .address = 0x84,
},
{
  .name = "MC_IO_RD_DQ_CNTL_I1",
  .address = 0x85,
},
{
  .name = "MC_IO_RD_QS_CNTL_I0",
  .address = 0x86,
},
{
  .name = "MC_IO_RD_QS_CNTL_I1",
  .address = 0x87,
},
{
  .name = "MC_IO_WR_CNTL_I0",
  .address = 0x88,
},
{
  .name = "MC_IO_WR_CNTL_I1",
  .address = 0x89,
},
{
  .name = "MC_IO_CK_PAD_CNTL_I0",
  .address = 0x8a,
},
{
  .name = "MC_IO_CK_PAD_CNTL_I1",
  .address = 0x8b,
},
{
  .name = "MC_IO_CMD_PAD_CNTL_I0",
  .address = 0x8c,
},
{
  .name = "MC_IO_CMD_PAD_CNTL_I1",
  .address = 0x8d,
},
{
  .name = "MC_IO_DQ_PAD_CNTL_I0",
  .address = 0x8e,
},
{
  .name = "MC_IO_DQ_PAD_CNTL_I1",
  .address = 0x8f,
},
{
  .name = "MC_CNTL1",
  .address = 0x9,
},
{
  .name = "MC_IO_QS_PAD_CNTL_I0",
  .address = 0x90,
},
{
  .name = "MC_IO_QS_PAD_CNTL_I1",
  .address = 0x91,
},
{
  .name = "MC_IO_A_PAD_CNTL_I0",
  .address = 0x92,
},
{
  .name = "MC_IO_A_PAD_CNTL_I1",
  .address = 0x93,
},
{
  .name = "MC_IO_WR_DQ_CNTL_I0",
  .address = 0x94,
},
{
  .name = "MC_IO_WR_DQ_CNTL_I1",
  .address = 0x95,
},
{
  .name = "MC_IO_WR_QS_CNTL_I0",
  .address = 0x96,
},
{
  .name = "MC_IO_WR_QS_CNTL_I1",
  .address = 0x97,
},
{
  .name = "MC_VENDOR_ID_I0",
  .address = 0x98,
},
{
  .name = "MC_VENDOR_ID_I1",
  .address = 0x99,
},
{
  .name = "MC_NPL_STATUS_I0",
  .address = 0x9a,
},
{
  .name = "MC_NPL_STATUS_I1",
  .address = 0x9b,
},
{
  .name = "MC_IO_RD_QS2_CNTL_I0",
  .address = 0x9c,
},
{
  .name = "MC_IO_RD_QS2_CNTL_I1",
  .address = 0x9d,
},
{
  .name = "MC_RFSH_CNTL",
  .address = 0xa,
},
{
  .name = "MC_IMP_CNTL",
  .address = 0xa0,
},
{
  .name = "MC_IMP_DEBUG",
  .address = 0xa1,
},
{
  .name = "MC_IMP_STATUS",
  .address = 0xa2,
},
{
  .name = "MC_RBS_MAP",
  .address = 0xb0,
},
{
  .name = "MC_RBS_CZT_HWM",
  .address = 0xb1,
},
{
  .name = "MC_RBS_SUN_HWM",
  .address = 0xb2,
},
{
  .name = "MC_RBS_MISC",
  .address = 0xb3,
},
{
  .name = "MC_PMG_CMD",
  .address = 0xe0,
},
{
  .name = "MC_PMG_CFG",
  .address = 0xe1,
},
{
  .name = "MC_MISC_0",
  .address = 0xf0,
},
{
  .name = "MC_MISC_1",
  .address = 0xf1,
},
{
  .name = "MC_DEBUG",
  .address = 0xfe,
},
